=== PriyankDhruv/Web_Technology/XML_Tutorials/Newspaper/Newspaper.dtd
<!DOCTYPE NEWSPAPER [
	<!ELEMENT NEWSPAPER(ARTICLE+)>
	<!ELEMENT ARTICLE(HEADLINE, BODY, NOTES)>
	<!ELEMENT HEADLINE(#PCDATA)>
	<!ELEMENT BODY(#PCDATA)>
	<!ELEMENT NOTES(#PCDATA)>
	<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
	<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
	]>

=== PriyankDhruv/Web_Technology/XML_Tutorials/Newspaper/Newspaper.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE NEWSPAPER SYSTEM "Newspaper.dtd">

<NEWSPAPER xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "Newspaper.xsd">
	<ARTICLE AUTHOR = "TOI" EDITOR = "TOL">
		<HEADLINE>ABC</HEADLINE>
		<BODY>Priyanshi is very intelliegent girl.</BODY>
		<NOTES>cutiepie</NOTES>
	</ARTICLE>
	<ARTICLE AUTHOR = "XOI" EDITOR = "XOL">
		<HEADLINE>XYZ</HEADLINE>
		<BODY>Dhruvi is very Brilliant girl.</BODY>
		<NOTES>honey</NOTES>
	</ARTICLE>
</NEWSPAPER>
